import { useCallback, useEffect, useMemo, useState } from 'react'
import { Pencil, Plus, Trash2, X } from 'lucide-react'
import api, { errorDetails } from '../services/api'
import PageHeader from '../components/PageHeader'
import { Alert, FieldError, Loading } from '../components/Feedback'
import ConfirmModal from '../components/ConfirmModal'
import { useTransientFeedback } from '../hooks/useTransientFeedback'

const configs = {
  'work-locations': { title: 'Work Locations', singular: 'work location', description: 'Manage the locations where volunteer work takes place.', columns: [['name', 'Name'], ['address', 'Address']], fields: [{ name: 'name', label: 'Name', required: true }, { name: 'address', label: 'Address' }] },
  tasks: { title: 'Tasks', singular: 'task', description: 'Manage the tasks available for volunteer assignments.', columns: [['name', 'Name'], ['description', 'Description']], fields: [{ name: 'name', label: 'Name', required: true }, { name: 'description', label: 'Description', type: 'textarea' }] },
  volunteers: { title: 'Volunteers', singular: 'volunteer', description: 'Manage volunteer profiles and linked login accounts.', columns: [['name', 'Name'], ['email', 'Email'], ['phone', 'Phone'], ['national_id', 'National ID']], fields: [{ name: 'name', label: 'Name', required: true }, { name: 'email', label: 'Email', type: 'email', required: true }, { name: 'phone', label: 'Phone', type: 'tel', required: true }, { name: 'national_id', label: 'National ID', required: true }, { name: 'password', label: 'Password', type: 'password', required: true, createOnly: true }, { name: 'password_confirmation', label: 'Confirm password', type: 'password', required: true, createOnly: true }] },
  assignments: { title: 'Assignments', singular: 'assignment', description: 'Connect volunteers with tasks, locations, and dates.', columns: [['volunteer.name', 'Volunteer'], ['task.name', 'Task'], ['work_location.name', 'Work location'], ['assignment_date', 'Date'], ['status', 'Status']], fields: [{ name: 'volunteer_id', label: 'Volunteer', type: 'select', source: '/volunteers', required: true, createOnly: true }, { name: 'task_id', label: 'Task', type: 'select', source: '/tasks', required: true }, { name: 'work_location_id', label: 'Work location', type: 'select', source: '/work-locations', required: true }, { name: 'assignment_date', label: 'Assignment date', type: 'date', required: true }] },
}
const getValue = (item, path) => path.split('.').reduce((value, key) => value?.[key], item) ?? '—'

function ResourceModal({ config, item, options, onClose, onSaved }) {
  const editing = Boolean(item)
  const activeFields = config.fields.filter((field) => !(editing && field.createOnly))
  const initial = useMemo(() => Object.fromEntries(activeFields.map((field) => [field.name, item ? (field.name.endsWith('_id') ? getValue(item, field.name.replace('_id', '.id')) : item[field.name] ?? '') : ''])), [activeFields, item])
  const [form, setForm] = useState(initial)
  const [feedback, setFeedback] = useTransientFeedback({ message: '', errors: {} })
  const [saving, setSaving] = useState(false)
  const submit = async (event) => { event.preventDefault(); setSaving(true); setFeedback({ message: '', errors: {} }); try { if (editing) await api.patch(`/${config.key}/${item.id}`, form); else await api.post(`/${config.key}`, form); onSaved(`${config.singular[0].toUpperCase() + config.singular.slice(1)} ${editing ? 'updated' : 'created'} successfully.`) } catch (error) { setFeedback(errorDetails(error)) } finally { setSaving(false) } }
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-4"><div role="dialog" aria-modal="true" className="card max-h-[90vh] w-full max-w-lg overflow-y-auto"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-4"><h2 className="text-lg font-semibold">{editing ? 'Edit' : 'Create'} {config.singular}</h2><button aria-label="Close" className="rounded p-1 hover:bg-slate-100" onClick={onClose}><X size={20} /></button></div><form className="space-y-4 p-6" onSubmit={submit}><Alert>{feedback.message}</Alert>{activeFields.map((field) => <div key={field.name}><label className="label" htmlFor={field.name}>{field.label}</label>{field.type === 'textarea' ? <textarea className="field min-h-24" id={field.name} required={field.required} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} /> : field.type === 'select' ? <select className="field" id={field.name} required={field.required} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })}><option value="">Select {field.label.toLowerCase()}</option>{(options[field.source] || []).map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select> : <input className="field" id={field.name} type={field.type || 'text'} required={field.required} value={form[field.name]} onChange={(e) => setForm({ ...form, [field.name]: e.target.value })} />}<FieldError errors={feedback.errors} name={field.name} /></div>)}<FieldError errors={feedback.errors} name="assignment" /><div className="flex justify-end gap-3 pt-2"><button type="button" className="btn-secondary" onClick={onClose}>Cancel</button><button className="btn-primary" disabled={saving}>{saving ? 'Saving…' : 'Save'}</button></div></form></div></div>
}

export default function ResourcePage({ resource }) {
  const config = useMemo(() => ({ ...configs[resource], key: resource }), [resource])
  const [items, setItems] = useState([]); const [options, setOptions] = useState({}); const [loading, setLoading] = useState(true); const [modal, setModal] = useState(undefined); const [deleteTarget, setDeleteTarget] = useState(null); const [deleting, setDeleting] = useState(false); const [feedback, setFeedback] = useTransientFeedback({ type: '', message: '' })
  const load = useCallback(async () => { setLoading(true); try { const { data } = await api.get(`/${resource}`); setItems(data.data) } catch (error) { setFeedback({ type: 'error', message: errorDetails(error).message }) } finally { setLoading(false) } }, [resource, setFeedback])
  useEffect(() => { load(); const sources = [...new Set(config.fields.map((field) => field.source).filter(Boolean))]; Promise.all(sources.map(async (source) => [source, (await api.get(source)).data.data])).then((entries) => setOptions(Object.fromEntries(entries))).catch(() => setFeedback({ type: 'error', message: 'Some form options could not be loaded.' })) }, [config.fields, load, setFeedback])
  const saved = (message) => { setModal(undefined); setFeedback({ type: 'success', message }); load() }
  const remove = async () => { if (!deleteTarget) return; setDeleting(true); try { const { data } = await api.delete(`/${resource}/${deleteTarget.id}`); setFeedback({ type: 'success', message: data.message }); setDeleteTarget(null); load() } catch (error) { setFeedback({ type: 'error', message: errorDetails(error).message }); setDeleteTarget(null) } finally { setDeleting(false) } }
  return <><PageHeader title={config.title} description={config.description} action={<button className="btn-primary" onClick={() => setModal(null)}><Plus size={17} />Create {config.singular}</button>} />{feedback.message && <div className="mb-4"><Alert type={feedback.type}>{feedback.message}</Alert></div>}{loading ? <Loading /> : <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr>{config.columns.map(([, label]) => <th className="px-5 py-3" key={label}>{label}</th>)}<th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr className="hover:bg-slate-50/70" key={item.id}>{config.columns.map(([key]) => <td className="max-w-xs px-5 py-4 text-slate-700" key={key}>{key === 'status' ? <span className="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-semibold capitalize text-amber-700">{getValue(item, key)}</span> : getValue(item, key)}</td>)}<td className="whitespace-nowrap px-5 py-3 text-right"><button className="rounded-lg p-2 text-slate-600 hover:bg-slate-100" aria-label={`Edit ${config.singular}`} onClick={() => setModal(item)}><Pencil size={16} /></button><button className="btn-danger" aria-label={`Delete ${config.singular}`} onClick={() => setDeleteTarget(item)}><Trash2 size={16} /></button></td></tr>)}{!items.length && <tr><td colSpan={config.columns.length + 1} className="px-5 py-12 text-center text-slate-500">No {config.title.toLowerCase()} found.</td></tr>}</tbody></table></div></div>}{modal !== undefined && <ResourceModal config={config} item={modal} options={options} onClose={() => setModal(undefined)} onSaved={saved} />}<ConfirmModal open={Boolean(deleteTarget)} title={`Delete ${config.singular}?`} message={`This will permanently delete ${deleteTarget?.name ? `“${deleteTarget.name}”` : `this ${config.singular}`}. This action cannot be undone.`} confirmLabel="Delete" busy={deleting} onCancel={() => setDeleteTarget(null)} onConfirm={remove} /></>
}
